### ISSUE TITLE
Questions about finding RA/DC in Tetra.c

### ISSUE THREAD

**Issue by jweisbaum** [brownj4/Tetra#2]
Comparing Tetra.c and tetra.py, I had a few questions about the differences.
1) Why does tetra.py have a fine map and course map, but tetra.c does not?
2) It looks like tetra.c is meant to compare 1000 images to their expected output, rather than to actually output the RA and Dec of the image. I'm trying to alter it to input an image and output the image's center RA/Dec. To find the RA/Dec of the image, is it just a matter of taking the [image_stars](https://github.com/brownj4/Tetra/blob/master/C_Tetra/Tetra.c#L835) vectors and finding a rotation matrix to the star's RA and Dec and then applying that to the vector (1,0,0)?
Thanks so much.

**Comment by brownj4** [comment]
The python version is an older implementation (a year older), which isn't as powerful as the C version.  Whereas the C version's wrapper code is for performance measurements, the python version implements every step of star tracking (i.e. centroiding, star ID, attitude determination).  That's what the fine and course sky maps are used for in the Python code, most notably rapidly finding unidentified stars in the image using an initial attitude estimate.  The sky maps are also used for speeding up iteration over all star patterns, but this is unnecessary in the C implementation due to optimizations at compile time.

The C implementation only performs the second step of star tracking, star ID, so it only outputs the catalog IDs of a subset of the stars in the image.  The rotation matrix can then be found by using the identified stars' catalog and image vectors.  I believe the rotation matrix is usually defined as [the matrix which left multiplies (1,0,0) to give the star camera's pointing in the catalog reference frame](https://github.com/brownj4/Tetra/blob/a00beda8925a256b25959474bb1030298d7e91cc/tetra.py#L662) (i.e. the reverse of what you said).  [The function that does this is only present in the python code.](https://github.com/brownj4/Tetra/blob/a00beda8925a256b25959474bb1030298d7e91cc/tetra.py#L599-L609)

**Comment by jweisbaum** [comment]
Awesome thanks so much!
